DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
  userid serial NOT NULL,
  username text NOT NULL,
  removed int DEFAULT 0,
  PRIMARY KEY (userid)
);

INSERT INTO users (username) VALUES
('Solomon Acquah'), 
('Benedicta Akakpo Dzidudu'),
('Abena Essah-Amoaful'),
('James Eli Doe'),
('Deborah Morklah'),
('Akosua Agyeibea Odei'),
('Portia Amoah'),
('Blessed Brister'),
('Emma Ohui Quansah'),
('Emmanuela Opokua Afari'),
('Daniel Essien'),
('Prince Alfred Gyan'),
('Linda Kabukie Olaga'),
('Esi Vic'),
('Emmanuel Nana otoo'),
('Barrister'),
('Maame Araba Arthur')
('Albert Essuman Pakum'),
('Abigail Baidoo'),
('Elvis Bentil'),
('Evangeline Stephens'),
('Richard Williams'),
('Sheila Adamptey'),
('Othniel Ben-Markin'),
('Cindy Aikins'),
('Rose Kaye'),
('Bright Donir'),
('Alfred Gyan'),
('Nana Yaa Akoma Amo-Addae'),
('Fortune Afaglo'),
('Hanson Akoto'),
('Joana Twum'),
('Nana Fynn'),
('Phillipa Edzoehoho A. Asamoah'),
('Chelsea Charlyn Kosoku'),
('Justica Mbgamsi'),
('Portia Opoku'),
('Benard Bass'),
('Rose - Nigeria'),
('Samuel Drummer')
('Priscilla -Prilla'),
('Mary Joanna'),
('Albert 2'),
('Jennifer'),
('Samuel Quansah'),
('Ruth Otipon Kem'),
('Ruth Ewuresi Oppong');